name: CI
on: [push, pull_request]

env:
  POETRY_HOME: /home/runner/.local
  POETRY_CACHE_DIR: /home/runner/.local/.cache

jobs:
  prepare:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up cache
        id: cached-dependencies
        uses: actions/cache@v2
        with:
          path: /home/runner/.local
          key: os-${{ matrix.os }}-python-${{ matrix.python-version}}-${{ hashFiles('**/poetry.lock') }}
      - name: Install Poetry
        if: steps.cached-dependencies.outputs.cache-hit != 'true'
        run: make install-poetry
      - name: Install packages
        if: steps.cached-dependencies.outputs.cache-hit != 'true'
        run: make install-packages opts="--no-root"

  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.local
          key: os-${{ matrix.os }}-python-${{ matrix.python-version}}-${{ hashFiles('**/poetry.lock') }}
      - name: Lint
        run: make lint

  tests:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        eventstoredb-version: ["21-10"]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.local
          key: os-${{ matrix.os }}-python-${{ matrix.python-version}}-${{ hashFiles('**/poetry.lock') }}
      - name: Start EventStoreDB
        run: |
          make start-eventstoredb-${{ matrix.eventstoredb-version}}
          sleep 60
      - name: Run tests
        run: make test
