name: CI
on: [push, pull_request]

env:
  POETRY_HOME: /home/runner/.local
  POETRY_CACHE_DIR: /home/runner/.local/.cache

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
        eventstoredb-version: [ "21-10" ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: make install-poetry
      - name: Install packages
        run: make install-packages
      - name: Start EventStoreDB
        run: |
          make start-eventstoredb-${{ matrix.eventstoredb-version}}
          sleep 60
      - name: Lint
        run: make lint
      - name: Test
        run: make test
